# Generated by Django 5.2.5 on 2025-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfumes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('launch_year', models.TextField(blank=True, null=True)),
                ('main_accords', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('longevity', models.JSONField(blank=True, null=True)),
                ('sillage', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfumes',
                'managed': False,
            },
        ),
    ]
