# Generated by Django 5.2.5 on 2025-08-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfumes',
            options={'managed': True},
        ),
    ]
